version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s:%(lineno)d] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  json:
    format: json
    class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: /home/SpharxWorkshop/workspace/logs/pipeline/main.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: /home/SpharxWorkshop/workspace/logs/errors/error.log
    maxBytes: 10485760
    backupCount: 3
    encoding: utf8

loggers:
  spharx:
    level: DEBUG
    handlers: [console, file, error_file]
    propagate: false
  
  pipelines:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console]