# COLMAP室内场景配置
[General]
use_gpu = 1
gpu_index = -1
snapshot_path = snapshots/
snapshot_images_freq = 100

[Database]
database_path = database.db

[ImageReader]
single_camera = 1
camera_model = SIMPLE_RADIAL
camera_params = 

[FeatureExtractor]
num_threads = -1
descriptor_normalization = l2
estimate_affine_shape = 0
max_num_features = 10000

[SequentialMatcher]
num_threads = -1
guided_matching = 1
overlap = 10

[Stereo]
num_threads = -1

[Fusion]
num_threads = -1
min_num_pixels = 5
max_image_size = 2000