# COLMAP室外场景配置
[General]
use_gpu = 1
gpu_index = -1
snapshot_path = snapshots/
snapshot_images_freq = 200

[Database]
database_path = database.db

[ImageReader]
single_camera = 0
camera_model = PINHOLE

[FeatureExtractor]
num_threads = -1
descriptor_normalization = l2
estimate_affine_shape = 1
max_num_features = 15000

[VocabTreeMatcher]
num_threads = -1
vocab_tree_path = vocab_tree.bin
num_checks = 100

[Stereo]
num_threads = -1

[Fusion]
num_threads = -1
min_num_pixels = 3
max_image_size = 3000